### ISSUE TITLE
How do I even specify what I want to render?

### ISSUE THREAD

**Issue by NoobTracker** [Friendly-Banana/no_render#1]
The mod doesn't seem to add a command or menu options, and it doesn't have ModMenu support. So, how do I tell the mod what to render? Do I need to change a config file that's hidden somewhere? Neither the curseforge page nor the github readme have any info on that. Maybe I'm just stupid / completely blind tho ^^

**Comment by NoobTracker** [comment]
Oh, found it, it's in .minecraft/config ... maybe mentioning that would help :)

**Comment by Friendly-Banana** [comment]
Thanks for mentioning this. I'll add it into the description for now and maybe look into mod menu support later.
