### ISSUE TITLE
Trying to hide entity with id

### ISSUE THREAD

**Issue by frankpadada** [Friendly-Banana/no_render#4]
Hi there, I tried to follow the mod description to hide entities with id, but everytime I save the toml and load the world it will reset to default and create a bak file. I've tried minecraft:creeper as well. Changing any other attributes will save and work correctly.
Game Version: 1.21.1
Mod loader: Fabric
What I am using the mod for: On the client side in a server, trying to hide 1000+ boats to avoid frame drop.
![image](https://github.com/user-attachments/assets/c1653736-1bbd-4aaa-80bc-80986188cc89)

**Comment by gkuznik** [comment]
Hey there,
you need to pass it as a string, like this `hiddenEntityIds = ["minecraft:creeper"]`. I will add an example to the description for this config to make it clearer.

**Comment by frankpadada** [comment]
:)Thanks for the reply. Now "minecraft:creeper" works but not any of the boats so I was wondering if this mod is only designed for mob entities

**Comment by gkuznik** [comment]
No, it should work on all entities. However it uses the entity id, and in 1.21.1 all boats regardless of their type have either `boat` or `chest_boat`. There is currently no way to hide only acacia, if you'd like this feature please let me know.
 `["minecraft:boat", "minecraft:chest_boat"]` hides all boats, I hope that's what you want :)
